export const timeout = 200;

/**
 * Latin - `[\u0300-\u036F]` matches combining diacritical marks:
 * - `\u0300-\u036F`: grave, acute, circumflex, tilde, macron, breve, dot above, diaeresis, ring above, etc.
 */
export const latinDiacritical = { tmp: '\uE000', pattern: '[\\u0300-\\u036F]*' };
/**
 * Arabic - `[\u064B-\u0652\u0670]` matches Arabic diacritics (harakat):
 * - `\u064B-\u0652`: fatha, damma, kasra, sukun, shadda, tanwin, etc.
 * - `\u0670`: alif khanjariyah (superscript alif)
 */
export const arabicDiacritical = { tmp: '\uE001', pattern: '[\\u064B-\\u0652\\u0670]*' };
/**
 * Hebrew - `[\u05B0-\u05BC\u05C1\u05C2]` matches Hebrew diacritics (niqqud):
 * - `\u05B0-\u05BC`: vowel points (sheva, hataf, hiriq, tsere, segol, patah, qamats, holam, qubuts, dagesh, etc.)
 * - `\u05C1-\u05C2`: shin dot (right) and sin dot (left)
 */
export const hebrewDiacritical = { tmp: '\uE002', pattern: '[\\u05B0-\\u05BC\\u05C1\\u05C2]*' };

export const unicodePatterns: { l: string; s: RegExp; e?: string; d?: { tmp: string; pattern: string } }[] = [
    // Latin
    { l: 'a', s: /[ⓐａẚàáâầấẫẩãāăằắẵẳȧǡäǟảåǻǎȁȃạậặḁąⱥɐ]/gi, e: 'a(?![aeouvy])', d: latinDiacritical },
    { l: 'aa', s: /ꜳ/gi, d: latinDiacritical },
    { l: 'ae', s: /[æǽǣ]/gi, d: latinDiacritical },
    { l: 'ao', s: /ꜵ/gi, d: latinDiacritical },
    { l: 'au', s: /ꜷ/gi, d: latinDiacritical },
    { l: 'av', s: /[ꜹꜻ]/gi, d: latinDiacritical },
    { l: 'ay', s: /ꜽ/gi, d: latinDiacritical },
    { l: 'b', s: /[ⓑｂḃḅḇƀƃɓ]/gi, d: latinDiacritical },
    { l: 'c', s: /[ⓒｃćĉċčçḉƈȼꜿↄ]/gi, d: latinDiacritical },
    { l: 'd', s: /[ⓓｄḋďḍḑḓḏđƌɖɗꝺ]/gi, e: 'd(?!z)', d: latinDiacritical },
    { l: 'dz', s: /[ǳǆ]/gi, d: latinDiacritical },
    { l: 'e', s: /(?<!o)[eⓔｅèéêềếễểẽēḕḗĕėëẻěȅȇẹệȩḝęḙḛɇɛǝ]/gi, e: '(?<!o)e', d: latinDiacritical },
    { l: 'f', s: /[ⓕｆḟƒꝼ]/gi, d: latinDiacritical },
    { l: 'g', s: /[ⓖｇǵĝḡğġǧģǥɠꞡᵹꝿ]/gi, d: latinDiacritical },
    { l: 'h', s: /[ⓗｈĥḣḧȟḥḩḫẖħⱨⱶɥ]/gi, e: 'h(?!v)', d: latinDiacritical },
    { l: 'hv', s: /ƕ/gi, d: latinDiacritical },
    { l: 'i', s: /[ⓘｉìíîĩīĭİïḯỉǐȉȋịįḭɨı]/gi, d: latinDiacritical },
    { l: 'j', s: /[ⓙｊĵǰɉ]/gi, e: '(?<![ln])j', d: latinDiacritical },
    { l: 'k', s: /[ⓚｋḱǩḳķḵƙⱪꝁꝃꝅꞣ]/gi, d: latinDiacritical },
    { l: 'l', s: /[ⓛｌŀĺľḷḹļḽḻſłƚɫⱡꝉꞁꝇꝆ]/gi, e: 'l(?!j)', d: latinDiacritical },
    { l: 'lj', s: /ǉ/gi, d: latinDiacritical },
    { l: 'm', s: /[ⓜｍḿṁṃɱɯ]/gi, d: latinDiacritical },
    { l: 'n', s: /[ⓝｎǹńñṅňṇņṋṉƞɲŉꞑꞥ]/gi, e: 'n(?!j)', d: latinDiacritical },
    { l: 'nj', s: /ǌ/gi, d: latinDiacritical },
    { l: 'o', s: /[ⓞｏòóôồốỗổõṍȭṏōṑṓŏȯȱöȫỏőǒȍȏơờớỡởợọộǫǭøǿɔƟꝋꝍɵ]/gi, e: 'o(?![ieou])', d: latinDiacritical },
    { l: 'oi', s: /ƣ/gi, d: latinDiacritical },
    { l: 'oe', s: /œ/gi, d: latinDiacritical },
    { l: 'oo', s: /ꝏ/gi, d: latinDiacritical },
    { l: 'ou', s: /ȣ/gi, d: latinDiacritical },
    { l: 'p', s: /[ⓟｐṕṗƥᵽꝑꝓꝕ]/gi, d: latinDiacritical },
    { l: 'q', s: /[ⓠｑɋꝗꝙ]/gi, d: latinDiacritical },
    { l: 'r', s: /[ⓡｒŕṙřȑȓṛṝŗṟɍɽꝛꞧꞃ]/gi, d: latinDiacritical },
    { l: 's', s: /[ⓢｓßẞśṥŝṡšṧṣṩșşȿꞩꞅẛ]/gi, d: latinDiacritical },
    { l: 't', s: /[ⓣｔṫẗťṭțţṱṯŧƭʈⱦꞇ]/gi, e: 't(?!z)', d: latinDiacritical },
    { l: 'tz', s: /ꜩ/gi, d: latinDiacritical },
    { l: 'u', s: /[ⓤｕùúûũṹūṻŭüǜǘǖǚủůűǔȕȗưừứữửựụṳųṷṵʉ]/gi, d: latinDiacritical },
    { l: 'v', s: /[ⓥｖṽṿʋꝟʌ]/gi, e: 'v(?!y)', d: latinDiacritical },
    { l: 'vy', s: /ꝡ/gi, d: latinDiacritical },
    { l: 'w', s: /[ⓦｗẁẃŵẇẅẘẉⱳ]/gi, d: latinDiacritical },
    { l: 'x', s: /[ⓧｘẋẍ]/gi, d: latinDiacritical },
    { l: 'y', s: /[ⓨｙỳýŷỹȳẏÿỷẙỵƴɏỿ]/gi, d: latinDiacritical },
    { l: 'z', s: /[ⓩｚźẑżžẓẕƶȥɀⱬꝣ]/gi, d: latinDiacritical },
    // Japanese - Hiragana/Katakana
    { l: 'あ', s: /[あアぁァ]゙?/gi },
    { l: 'い', s: /[いイぃィ]゙?/gi },
    { l: 'う', s: /[うウぅゥゔヴ]゙?/gi },
    { l: 'え', s: /[えエぇェ]゙?/gi },
    { l: 'お', s: /[おオぉォ]゙?/gi },
    { l: 'か', s: /[かカがガゕヵ]゙?/gi },
    { l: 'き', s: /[きキぎギ]゙?/gi },
    { l: 'く', s: /[くクぐグ]゙?/gi },
    { l: 'け', s: /[けケげゲゖヶ]゙?/gi },
    { l: 'こ', s: /[こコごゴ]゙?/gi },
    { l: 'さ', s: /[さサざザ]゙?/gi },
    { l: 'し', s: /[しシじジ]゙?/gi },
    { l: 'す', s: /[すスずズ]゙?/gi },
    { l: 'せ', s: /[せセぜゼ]゙?/gi },
    { l: 'そ', s: /[そソぞゾ]゙?/gi },
    { l: 'た', s: /[たタだダ]゙?/gi },
    { l: 'ち', s: /[ちチぢヂ]゙?/gi },
    { l: 'つ', s: /[つツっッづヅ]゙?/gi },
    { l: 'て', s: /[てテでデ]゙?/gi },
    { l: 'と', s: /[とトどド]゙?/gi },
    { l: 'な', s: /ナ/gi },
    { l: 'に', s: /ニ/gi },
    { l: 'ぬ', s: /ヌ/gi },
    { l: 'ね', s: /ネ/gi },
    { l: 'の', s: /ノ/gi },
    { l: 'は', s: /[はハばバぱパ][゙゚]?/gi },
    { l: 'ひ', s: /[ひヒびビぴピ][゙゚]?/gi },
    { l: 'ふ', s: /[ふフぶブぷプ][゙゚]?/gi },
    { l: 'へ', s: /[へヘべベぺペ][゙゚]?/gi },
    { l: 'ほ', s: /[ほホぼボぽポ][゙゚]?/gi },
    { l: 'ま', s: /マ/gi },
    { l: 'み', s: /ミ/gi },
    { l: 'む', s: /ム/gi },
    { l: 'め', s: /メ/gi },
    { l: 'も', s: /モ/gi },
    { l: 'や', s: /[ヤゃャ]/gi },
    { l: 'ゆ', s: /[ユゅュ]/gi },
    { l: 'よ', s: /[ヨょョ]/gi },
    { l: 'ら', s: /ラ/gi },
    { l: 'り', s: /リ/gi },
    { l: 'る', s: /ル/gi },
    { l: 'れ', s: /レ/gi },
    { l: 'ろ', s: /ロ/gi },
    { l: 'わ', s: /[わワゎヮヷ]゙?/gi },
    { l: 'ゐ', s: /[ゐヰヸ]゙?/gi },
    { l: 'ゑ', s: /[ゑヱヹ]゙?/gi },
    { l: 'を', s: /[をヲヺ]゙?/gi },
    { l: 'ん', s: /[ン]/gi },
    // Cyrillic
    { l: 'а', s: /[аӐӑӒӓӔӕ]/gi },
    { l: 'г', s: /[гѓґҐғҒҕҔ]/gi },
    { l: 'д', s: /[дђѐ]/gi },
    { l: 'е', s: /[еѐёЁӖӗ]/gi },
    { l: 'ж', s: /[жӁӂӜӝ]/gi },
    { l: 'з', s: /[зӞӟ]/gi },
    { l: 'и', s: /[иѝӢӣӤӥ]/gi },
    { l: 'й', s: /[йЙ]/gi },
    { l: 'к', s: /[кќҚқҜҝҞҟҠҡ]/gi },
    { l: 'л', s: /[лљЉ]/gi },
    { l: 'н', s: /[нњЊҢңӉӊ]/gi },
    { l: 'о', s: /[оӦӧӨӫ]/gi },
    { l: 'с', s: /[сҪҫ]/gi },
    { l: 'т', s: /[тћЋ]/gi },
    { l: 'у', s: /[уўЎӮӯӰӱӲӳ]/gi },
    { l: 'х', s: /[хҲҳӇӈ]/gi },
    { l: 'ч', s: /[чҴҵӴӵ]/gi },
    { l: 'ы', s: /[ыӸӹ]/gi },
    // Greek
    { l: 'α', s: /[αάἀἁἂἃἄἅἆἇὰάᾀᾁᾂᾃᾄᾅᾆᾇᾰᾱᾲᾳᾴᾶᾷ]/gi },
    { l: 'β', s: /[βϐ]/gi },
    { l: 'η', s: /[ηήἠἡἢἣἤἥἦἧὴήᾐᾑᾒᾓᾔᾕᾖᾗῂῃῄῆῇ]/gi },
    { l: 'θ', s: /[θϑ]/gi },
    { l: 'ι', s: /[ιίϊΐἰἱἲἳἴἵἶἷὶίῐῑῒΐῖῗ]/gi },
    { l: 'κ', s: /[κϰ]/gi },
    { l: 'ο', s: /[οόὀὁὂὃὄὅὸό]/gi },
    { l: 'π', s: /[πϖ]/gi },
    { l: 'ρ', s: /[ρϱῤῥ]/gi },
    { l: 'σ', s: /[σςϲ]/gi },
    { l: 'υ', s: /[υύϋΰὐὑὒὓὔὕὖὗὺύῠῡῢΰῦῧ]/gi },
    { l: 'φ', s: /[φϕ]/gi },
    { l: 'ω', s: /[ωώὠὡὢὣὤὥὦὧὼώᾠᾡᾢᾣᾤᾥᾦᾧῲῳῴῶῷ]/gi },
    // Arabic
    { l: 'ا', s: /[اأإآٱ]/gi, d: arabicDiacritical },
    { l: 'ب', s: /ب/gi, d: arabicDiacritical },
    { l: 'ت', s: /[تة]/gi, d: arabicDiacritical },
    { l: 'ث', s: /ث/gi, d: arabicDiacritical },
    { l: 'ج', s: /ج/gi, d: arabicDiacritical },
    { l: 'ح', s: /ح/gi, d: arabicDiacritical },
    { l: 'خ', s: /خ/gi, d: arabicDiacritical },
    { l: 'د', s: /د/gi, d: arabicDiacritical },
    { l: 'ذ', s: /ذ/gi, d: arabicDiacritical },
    { l: 'ر', s: /ر/gi, d: arabicDiacritical },
    { l: 'ز', s: /ز/gi, d: arabicDiacritical },
    { l: 'س', s: /س/gi, d: arabicDiacritical },
    { l: 'ش', s: /ش/gi, d: arabicDiacritical },
    { l: 'ص', s: /ص/gi, d: arabicDiacritical },
    { l: 'ض', s: /ض/gi, d: arabicDiacritical },
    { l: 'ط', s: /ط/gi, d: arabicDiacritical },
    { l: 'ظ', s: /ظ/gi, d: arabicDiacritical },
    { l: 'ع', s: /ع/gi, d: arabicDiacritical },
    { l: 'غ', s: /غ/gi, d: arabicDiacritical },
    { l: 'ف', s: /ف/gi, d: arabicDiacritical },
    { l: 'ق', s: /ق/gi, d: arabicDiacritical },
    { l: 'ك', s: /[كک]/gi, d: arabicDiacritical },
    { l: 'ل', s: /ل/gi, d: arabicDiacritical },
    { l: 'م', s: /م/gi, d: arabicDiacritical },
    { l: 'ن', s: /ن/gi, d: arabicDiacritical },
    { l: 'ه', s: /[هە]/gi, d: arabicDiacritical },
    { l: 'و', s: /[وؤ]/gi, d: arabicDiacritical },
    { l: 'ي', s: /[يىئ]/gi, d: arabicDiacritical },
    // Hebrew
    { l: 'א', s: /א/gi, d: hebrewDiacritical },
    { l: 'ב', s: /ב/gi, d: hebrewDiacritical },
    { l: 'ג', s: /ג/gi, d: hebrewDiacritical },
    { l: 'ד', s: /ד/gi, d: hebrewDiacritical },
    { l: 'ה', s: /ה/gi, d: hebrewDiacritical },
    { l: 'ו', s: /ו/gi, d: hebrewDiacritical },
    { l: 'ז', s: /ז/gi, d: hebrewDiacritical },
    { l: 'ח', s: /ח/gi, d: hebrewDiacritical },
    { l: 'ט', s: /ט/gi, d: hebrewDiacritical },
    { l: 'י', s: /י/gi, d: hebrewDiacritical },
    { l: 'כ', s: /[כך]/gi, d: hebrewDiacritical },
    { l: 'ל', s: /ל/gi, d: hebrewDiacritical },
    { l: 'מ', s: /[םמ]/gi, d: hebrewDiacritical },
    { l: 'נ', s: /[ןנ]/gi, d: hebrewDiacritical },
    { l: 'ס', s: /ס/gi, d: hebrewDiacritical },
    { l: 'ע', s: /ע/gi, d: hebrewDiacritical },
    { l: 'פ', s: /[פף]/gi, d: hebrewDiacritical },
    { l: 'צ', s: /[ץצ]/gi, d: hebrewDiacritical },
    { l: 'ק', s: /ק/gi, d: hebrewDiacritical },
    { l: 'ר', s: /ר/gi, d: hebrewDiacritical },
    { l: 'ש', s: /ש/gi, d: hebrewDiacritical },
    { l: 'ת', s: /ת/gi, d: hebrewDiacritical },
];

export const defaultMinCountForSearch = 6;

export const protectRegexp = new RegExp('[\\-\\[\\]\\/\\{\\}\\(\\)\\*\\+\\?\\.\\\\\\^\\$\\|]', 'g');
